### ISSUE TITLE
Update to new API

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/pytket-iqm#40]

**Comment by cqc-melf** [comment]
The API has been changed, we will need update out interaction with it.

**Comment by cqc-melf** [comment]
might want to update to iqm-client 9.3, too?

**Comment by cqc-melf** [comment]
Update to the new iqm client https://github.com/iqm-finland/iqm-client/releases/tag/12.0

**Comment by cqc-alec** [comment]
Test failing with:

```
ValueError: 'pending execution' is not a valid Status
```
